stages:
  - 'test'

variables:
  COMPOSER_COMMAND: '/var/www/html/composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader'
  BASE_PHP_VERSION: '8.1'
  PLUGIN_NAME: 'BasecomFixturePlugin'
  PLUGIN_COMPOSER_NAME: 'basecom/sw6-fixtures-plugin'

# STAGE TEST
test php cs fixer:
  stage: 'test'
  image: 'dockware/flex:latest'
  before_script:
    - '(cd /var/www && make switch-php version=${BASE_PHP_VERSION})'
    - 'php -v'
    - 'composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader'
  script:
    - './vendor/bin/php-cs-fixer fix --dry-run'

test phpstan:
  stage: 'test'
  image: 'dockware/flex:latest'
  parallel:
    matrix:
      - PHP_VERSION: ['7.4', '8.0', '8.1']
  before_script:
    - '(cd /var/www && make switch-php version=${PHP_VERSION})'
    - 'php -v'
    - 'composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader'
  script:
    - './vendor/bin/phpstan analyse --memory-limit=1G'

test psalm:
  stage: 'test'
  image: 'dockware/flex:latest'
  before_script:
    - '(cd /var/www && make switch-php version=${BASE_PHP_VERSION})'
    - 'php -v'
    - 'composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader'
  script:
    - './vendor/bin/psalm --show-info=false'

test prettier:
  stage: 'test'
  image: 'dockware/flex:latest'
  before_script:
    - 'npm ci'
  script:
    - './node_modules/.bin/prettier --check "src/**/*.{js,scss,yaml,yml,json,md,ts}"'
