services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Basecom\FixturePlugin\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,spec}'
